table fct_antes
	lineageTag: d4e7e63e-b7ca-40a2-a8f8-698bb06b503d

	measure 'Total Respuestas' = COUNT(fct_antes[survey_response_id])
		lineageTag: e09986ae-93c7-4ca8-90ec-7675bca77faa

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Total Conteo' = ```
			
			DIVIDE(
			    COUNT(fct_antes[survey_response_id]), 
			    CALCULATE(
			        COUNT(fct_antes[survey_response_id]), 
			        ALL(fct_antes)
			    ), 
			    0
			)
			```
		formatString: 0%;-0%;0%
		lineageTag: efced14c-92a4-405b-9fa3-d86aef167581

	column survey_response_id
		dataType: int64
		formatString: 0
		lineageTag: 79e676c5-5310-4752-bf19-3b988965550c
		summarizeBy: none
		sourceColumn: survey_response_id

		annotation SummarizationSetBy = Automatic

	column fecha_hora
		dataType: dateTime
		formatString: Short Date
		lineageTag: b60a56c5-8a5e-4e47-87af-b0f7bba335a3
		summarizeBy: none
		sourceColumn: fecha_hora

		annotation SummarizationSetBy = Automatic

	column fecha_hora_fin
		dataType: dateTime
		formatString: General Date
		lineageTag: 96f1255b-acd2-473c-934e-2ff081ec488d
		summarizeBy: none
		sourceColumn: fecha_hora_fin

		annotation SummarizationSetBy = Automatic

	column fecha
		dataType: dateTime
		formatString: Long Date
		lineageTag: 7d255731-83a5-4309-b5d0-765378f1b06f
		summarizeBy: none
		sourceColumn: fecha

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column question_id
		dataType: int64
		formatString: 0
		lineageTag: 47cba758-e6d1-4e44-af84-7f066682b016
		summarizeBy: none
		sourceColumn: question_id

		annotation SummarizationSetBy = Automatic

	column depends_on_question_id
		dataType: int64
		formatString: 0
		lineageTag: d1f7d4ae-0716-4def-9643-3c82a14f801a
		summarizeBy: sum
		sourceColumn: depends_on_question_id

		annotation SummarizationSetBy = Automatic

	column photo_question_id
		dataType: int64
		formatString: 0
		lineageTag: 16e12664-36ed-4912-a1a6-77b9667ab58a
		summarizeBy: sum
		sourceColumn: photo_question_id

		annotation SummarizationSetBy = Automatic

	column quiz_id
		dataType: int64
		formatString: 0
		lineageTag: 0a1c00e6-326d-437e-85aa-3335b656c323
		summarizeBy: sum
		sourceColumn: quiz_id

		annotation SummarizationSetBy = Automatic

	column user_id
		dataType: int64
		formatString: 0
		lineageTag: bf9dd382-370d-4ba4-b4be-7170ee1b2e31
		summarizeBy: none
		sourceColumn: user_id

		annotation SummarizationSetBy = Automatic

	column branch_id
		dataType: int64
		formatString: 0
		lineageTag: 69fa6394-4ea9-4091-8ce1-fd2a5d0cc874
		summarizeBy: none
		sourceColumn: branch_id

		annotation SummarizationSetBy = Automatic

	column answer
		dataType: string
		lineageTag: 2f9dda47-2062-4a78-85f3-e1a5205e5286
		summarizeBy: none
		sourceColumn: answer

		annotation SummarizationSetBy = Automatic

	column answer_integer
		dataType: int64
		formatString: 0
		lineageTag: a74abcbe-72a8-4f3b-99d0-c08d4ee7aa81
		summarizeBy: sum
		sourceColumn: answer_integer

		annotation SummarizationSetBy = Automatic

	column product_id
		dataType: int64
		formatString: 0
		lineageTag: a4c733b6-d511-475d-aabe-933a53d49bb8
		summarizeBy: sum
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column has_score
		dataType: int64
		formatString: 0
		lineageTag: 6730d983-906e-401b-8a75-00333e019932
		summarizeBy: sum
		sourceColumn: has_score

		annotation SummarizationSetBy = Automatic

	column obtained_score
		dataType: double
		lineageTag: 7a27c79e-f0f0-46cc-8947-f00c5461ea00
		summarizeBy: sum
		sourceColumn: obtained_score

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column question_total_score
		dataType: double
		lineageTag: c160b676-a63c-47d8-918e-c497320f59bc
		summarizeBy: sum
		sourceColumn: question_total_score

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column category
		dataType: string
		lineageTag: 4c3975df-189b-4acf-9198-8607fe450233
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column sub_category
		dataType: string
		lineageTag: 62f1385b-001f-494f-a0a3-28e740226c0c
		summarizeBy: none
		sourceColumn: sub_category

		annotation SummarizationSetBy = Automatic

	column modulo
		dataType: int64
		formatString: 0
		lineageTag: eca7984b-94cb-4bb2-bcf6-c9e00c43c173
		summarizeBy: sum
		sourceColumn: modulo

		annotation SummarizationSetBy = Automatic

	column question_response_id
		dataType: int64
		formatString: 0
		lineageTag: c6120899-42c0-4530-a957-297a23b97d98
		summarizeBy: sum
		sourceColumn: question_response_id

		annotation SummarizationSetBy = Automatic

	column comment_teleaudit
		dataType: string
		lineageTag: 9187a41a-55aa-439c-ab75-27c590911a1c
		summarizeBy: none
		sourceColumn: comment_teleaudit

		annotation SummarizationSetBy = Automatic

	column response_is_approved
		dataType: int64
		formatString: 0
		lineageTag: 742d5240-99e4-4482-a75a-70b93c5e6367
		summarizeBy: sum
		sourceColumn: response_is_approved

		annotation SummarizationSetBy = Automatic

	column app
		dataType: string
		lineageTag: a383628a-19c4-4dac-9bc2-bf9a02ee5b36
		summarizeBy: none
		sourceColumn: app

		annotation SummarizationSetBy = Automatic

	column kpi_id
		dataType: int64
		formatString: 0
		lineageTag: 8c8eefe7-2c0b-4e69-b827-a2b3d681afca
		summarizeBy: sum
		sourceColumn: kpi_id

		annotation SummarizationSetBy = Automatic

	column is_image
		dataType: int64
		formatString: 0
		lineageTag: db212911-92a6-43d3-8c85-9b6de921b2b5
		summarizeBy: sum
		sourceColumn: is_image

		annotation SummarizationSetBy = Automatic

	column is_video
		dataType: int64
		formatString: 0
		lineageTag: 7cf9d9e6-4770-4dfd-8768-12952e4ba34c
		summarizeBy: sum
		sourceColumn: is_video

		annotation SummarizationSetBy = Automatic

	column is_audio
		dataType: int64
		formatString: 0
		lineageTag: d51a2605-880e-492c-906d-1aa7e56c3465
		summarizeBy: sum
		sourceColumn: is_audio

		annotation SummarizationSetBy = Automatic

	column is_comment
		dataType: int64
		formatString: 0
		lineageTag: 444b932b-965b-477e-862d-e7e242403b50
		summarizeBy: sum
		sourceColumn: is_comment

		annotation SummarizationSetBy = Automatic

	column orden_foto_question
		dataType: int64
		formatString: 0
		lineageTag: 07b02d3a-2cab-4fac-a79b-8756fb20e621
		summarizeBy: sum
		sourceColumn: orden_foto_question

		annotation SummarizationSetBy = Automatic

	column question_category
		dataType: string
		lineageTag: 0af79228-bf20-459d-b27d-ab00b600e81e
		summarizeBy: none
		sourceColumn: question_category

		annotation SummarizationSetBy = Automatic

	column quiz_category
		dataType: string
		lineageTag: 27f706d3-85d4-401e-bc7b-43950da2c9ff
		summarizeBy: none
		sourceColumn: quiz_category

		annotation SummarizationSetBy = Automatic

	column medicion
		dataType: int64
		formatString: 0
		lineageTag: 23bea5e3-4690-4e55-8b86-830c1fa446f5
		summarizeBy: sum
		sourceColumn: medicion

		annotation SummarizationSetBy = Automatic

	column survey_response_despues
		dataType: int64
		formatString: 0
		lineageTag: 0d6f423a-9a1a-4c64-bd5f-bb5129ba1d2d
		summarizeBy: sum
		sourceColumn: survey_response_despues

		annotation SummarizationSetBy = Automatic

	column survey_response_review
		dataType: int64
		formatString: 0
		lineageTag: 4a3fa898-f319-4bcc-aa6d-38c4c3588225
		summarizeBy: none
		sourceColumn: survey_response_review

		annotation SummarizationSetBy = Automatic

	column imagen =
			
			CALCULATE(
			    MAX(fct_antes[answer]),
			    FILTER(
			        fct_antes,
			            fct_antes[survey_response_id] = EARLIER(fct_antes[survey_response_id])
			            && fct_antes[question_category] = "Imagen"
			    )
			)
		lineageTag: 226d6056-0a95-4b1f-8ace-c020976e2262
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column descripcion =
			
			CALCULATE(
			    MAX(fct_antes[answer]),
			    FILTER(
			        fct_antes,
			            fct_antes[survey_response_id] = EARLIER(fct_antes[survey_response_id])
			            && fct_antes[question_category] = "Descripcion"
			    )
			)
		lineageTag: 24c0d014-4e01-4c3c-aa0e-2c9fdb3a5aaf
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Usuario = RELATED(dim_usuarios[name])
		lineageTag: 2510860c-e4f4-4b84-870d-7ad5d1d87729
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column tipo_oportunidad =
			
			CALCULATE(
			    MAX(fct_antes[answer]),
			    FILTER(
			        fct_antes,
			            fct_antes[survey_response_id] = EARLIER(fct_antes[survey_response_id])
			            && fct_antes[question_category] = "Tipo-Oportunidad"
			    )
			)
		lineageTag: 808a3d05-343d-4859-805c-b4ab9de3c841
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Sucursal = RELATED(dim_sucursales[name])
		lineageTag: 581e747f-a2bc-48bb-b18a-6deb2d501475
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Periodo = FORMAT(fct_antes[fecha_hora],"yyyy-mm")
		lineageTag: 9c07425f-dd4a-4c93-9464-d560e3228fd7
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Periodo_m =
			
			VAR periodo = fct_antes[Periodo]
			VAR medicion = CONCATENATE("Med 0",fct_antes[medicion])
			RETURN
			medicion
		lineageTag: 5e80d61e-5b48-4182-8e6c-27a3d98ac9a1
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Comuna = RELATED(dim_sucursales[city])
		lineageTag: da7fc556-8361-4816-85ad-6b676fa935a3
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition fct_antes = m
		mode: import
		queryGroup: Fcts
		source =
				let
				    Origen = fct_respuestas,
				    #"Filas filtradas" = Table.SelectRows(Origen, each ([quiz_category] = "Antes") and ([survey_response_id] <> 202875 and [survey_response_id] <> 219097))
				in
				    #"Filas filtradas"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Exception

