table fct_despues
	lineageTag: 05a92689-25ef-420b-89b0-55ccf8232e36

	column survey_response_id
		dataType: int64
		formatString: 0
		lineageTag: acb3f41d-b412-4a8f-8cf9-6563d56b3bfc
		summarizeBy: none
		sourceColumn: survey_response_id

		annotation SummarizationSetBy = Automatic

	column fecha_hora
		dataType: dateTime
		formatString: General Date
		lineageTag: 0fb05a8f-6eaa-45f6-88ac-8b77355d9763
		summarizeBy: none
		sourceColumn: fecha_hora

		annotation SummarizationSetBy = Automatic

	column fecha_hora_fin
		dataType: dateTime
		formatString: General Date
		lineageTag: c6efd4f2-aea7-4a5a-81c2-dab3ce0c3c00
		summarizeBy: none
		sourceColumn: fecha_hora_fin

		annotation SummarizationSetBy = Automatic

	column fecha
		dataType: dateTime
		formatString: Long Date
		lineageTag: 28dbe5c9-27de-4101-9500-e62ddd1b6856
		summarizeBy: none
		sourceColumn: fecha

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column question_id
		dataType: int64
		formatString: 0
		lineageTag: 8322a819-baba-42fc-8e70-7528efcc7b2a
		summarizeBy: sum
		sourceColumn: question_id

		annotation SummarizationSetBy = Automatic

	column depends_on_question_id
		dataType: int64
		formatString: 0
		lineageTag: fa111f5b-de99-477a-b732-51d5e405bd90
		summarizeBy: sum
		sourceColumn: depends_on_question_id

		annotation SummarizationSetBy = Automatic

	column photo_question_id
		dataType: int64
		formatString: 0
		lineageTag: 723c2315-f50d-4950-b9f1-229ae90016be
		summarizeBy: sum
		sourceColumn: photo_question_id

		annotation SummarizationSetBy = Automatic

	column quiz_id
		dataType: int64
		formatString: 0
		lineageTag: cffb087e-9187-4e26-ad05-e9d08cc8b595
		summarizeBy: sum
		sourceColumn: quiz_id

		annotation SummarizationSetBy = Automatic

	column user_id
		dataType: int64
		formatString: 0
		lineageTag: a0a9eac4-7704-43b3-bc64-a6c642c5f710
		summarizeBy: sum
		sourceColumn: user_id

		annotation SummarizationSetBy = Automatic

	column branch_id
		dataType: int64
		formatString: 0
		lineageTag: b797c626-bb8f-4ee1-91c3-e6de74072c68
		summarizeBy: sum
		sourceColumn: branch_id

		annotation SummarizationSetBy = Automatic

	column answer
		dataType: string
		lineageTag: a6418d4c-c9ca-4f76-bdd8-bcb7c7d8a718
		summarizeBy: none
		sourceColumn: answer

		annotation SummarizationSetBy = Automatic

	column answer_integer
		dataType: int64
		formatString: 0
		lineageTag: 4cc9ad40-236f-4caf-9336-2be7f33bcccd
		summarizeBy: sum
		sourceColumn: answer_integer

		annotation SummarizationSetBy = Automatic

	column product_id
		dataType: int64
		formatString: 0
		lineageTag: d94c02af-dbfe-43e1-8537-2b19b73735b8
		summarizeBy: sum
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column has_score
		dataType: int64
		formatString: 0
		lineageTag: 5c073296-d4a6-4611-8cdb-55fa49c8ea44
		summarizeBy: sum
		sourceColumn: has_score

		annotation SummarizationSetBy = Automatic

	column obtained_score
		dataType: double
		lineageTag: d2a5565e-13d7-4e75-90c8-8032678d0619
		summarizeBy: sum
		sourceColumn: obtained_score

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column question_total_score
		dataType: double
		lineageTag: 7cb312db-e37f-412b-b35a-2375e49dc7d0
		summarizeBy: sum
		sourceColumn: question_total_score

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column category
		dataType: string
		lineageTag: 8b814e97-908b-4585-9f59-dd6b8e580d47
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column sub_category
		dataType: string
		lineageTag: 285e5f3a-c571-4a25-99c5-495238464361
		summarizeBy: none
		sourceColumn: sub_category

		annotation SummarizationSetBy = Automatic

	column modulo
		dataType: int64
		formatString: 0
		lineageTag: dbdfd407-e4f3-47bc-928f-e50bb6d980f3
		summarizeBy: sum
		sourceColumn: modulo

		annotation SummarizationSetBy = Automatic

	column question_response_id
		dataType: int64
		formatString: 0
		lineageTag: b6aef2dd-2ebe-4788-856a-f21fabcd56b3
		summarizeBy: sum
		sourceColumn: question_response_id

		annotation SummarizationSetBy = Automatic

	column comment_teleaudit
		dataType: string
		lineageTag: 1566b085-7267-48b9-9df0-ff638741c6fc
		summarizeBy: none
		sourceColumn: comment_teleaudit

		annotation SummarizationSetBy = Automatic

	column response_is_approved
		dataType: int64
		formatString: 0
		lineageTag: 14324da3-22a9-4c88-84ed-d77c669fbc77
		summarizeBy: sum
		sourceColumn: response_is_approved

		annotation SummarizationSetBy = Automatic

	column app
		dataType: string
		lineageTag: f3613d52-2bfa-42b0-b3e7-fb94c525ccbe
		summarizeBy: none
		sourceColumn: app

		annotation SummarizationSetBy = Automatic

	column kpi_id
		dataType: int64
		formatString: 0
		lineageTag: 164fd99b-e758-4af5-8fd6-3dbf94fc9107
		summarizeBy: sum
		sourceColumn: kpi_id

		annotation SummarizationSetBy = Automatic

	column is_image
		dataType: int64
		formatString: 0
		lineageTag: d4fea094-6050-4182-8a61-85baadbda1a3
		summarizeBy: sum
		sourceColumn: is_image

		annotation SummarizationSetBy = Automatic

	column is_video
		dataType: int64
		formatString: 0
		lineageTag: f28b2642-4099-41ae-9628-2cb0788f3e1d
		summarizeBy: sum
		sourceColumn: is_video

		annotation SummarizationSetBy = Automatic

	column is_audio
		dataType: int64
		formatString: 0
		lineageTag: 3d26b479-dc80-41ea-8029-8c7e902f6573
		summarizeBy: sum
		sourceColumn: is_audio

		annotation SummarizationSetBy = Automatic

	column is_comment
		dataType: int64
		formatString: 0
		lineageTag: e4b68f9b-82d5-4f6b-91a6-3870d7cb04d6
		summarizeBy: sum
		sourceColumn: is_comment

		annotation SummarizationSetBy = Automatic

	column orden_foto_question
		dataType: int64
		formatString: 0
		lineageTag: e40e912f-4da0-4191-b351-8e1b039fb33d
		summarizeBy: sum
		sourceColumn: orden_foto_question

		annotation SummarizationSetBy = Automatic

	column question_category
		dataType: string
		lineageTag: 60b0a886-2da1-4cee-81fb-b7b098ca8fd3
		summarizeBy: none
		sourceColumn: question_category

		annotation SummarizationSetBy = Automatic

	column quiz_category
		dataType: string
		lineageTag: 38591817-084c-4033-a045-51a07fce5d86
		summarizeBy: none
		sourceColumn: quiz_category

		annotation SummarizationSetBy = Automatic

	column medicion
		dataType: int64
		formatString: 0
		lineageTag: 34e7406c-3d22-4f7f-82b8-6c95d4b81e78
		summarizeBy: sum
		sourceColumn: medicion

		annotation SummarizationSetBy = Automatic

	column imagen =
			
			CALCULATE(
			    MAX(fct_despues[answer]),
			    FILTER(
			        fct_despues,
			            fct_despues[survey_response_id] = EARLIER(fct_despues[survey_response_id])
			            && fct_despues[question_category] = "Imagen"
			    )
			)
		lineageTag: 360eccb5-09a4-4e63-a767-47d23fa45ce1
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column descripcion =
			
			CALCULATE(
			    MAX(fct_despues[answer]),
			    FILTER(
			        fct_despues,
			            fct_despues[survey_response_id] = EARLIER(fct_despues[survey_response_id])
			            && fct_despues[question_category] = "Descripcion"
			    )
			)
		lineageTag: 41986465-9296-4344-8e1a-598a982a82c0
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition fct_despues = m
		mode: import
		queryGroup: Fcts
		source =
				let
				    Origen = fct_respuestas,
				    #"Filas filtradas" = Table.SelectRows(Origen, each [quiz_category] = "Después"),
				    #"Otras columnas quitadas" = Table.SelectColumns(#"Filas filtradas",{"survey_response_id", "fecha_hora", "fecha_hora_fin", "fecha", "question_id", "depends_on_question_id", "photo_question_id", "quiz_id", "user_id", "branch_id", "answer", "answer_integer", "product_id", "has_score", "obtained_score", "question_total_score", "category", "sub_category", "modulo", "question_response_id", "comment_teleaudit", "response_is_approved", "app", "kpi_id", "is_image", "is_video", "is_audio", "is_comment", "orden_foto_question", "question_category", "quiz_category", "medicion"}),
				    #"Filas filtradas1" = Table.SelectRows(#"Otras columnas quitadas", each ([survey_response_id] <> 203916))
				in
				    #"Filas filtradas1"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Exception

