table Mantenimiento
	lineageTag: 3d08cdf0-8588-4809-899a-6d6c71ff8947

	column branch_id
		dataType: int64
		formatString: 0
		lineageTag: 5f22d47b-45dd-4c49-8131-caac1bb0a358
		summarizeBy: none
		sourceColumn: branch_id

		annotation SummarizationSetBy = Automatic

	column fecha
		dataType: dateTime
		formatString: Short Date
		lineageTag: 5e50b08a-c86d-4f41-a09a-3beae48f3ccd
		summarizeBy: none
		sourceColumn: fecha

		variation Variación
			isDefault
			relationship: 25769aca-c605-47a2-9c08-2461a3179a39
			defaultHierarchy: LocalDateTable_718b3aa1-a948-40f7-82f8-d876c14aa015.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column response_id
		dataType: string
		lineageTag: 920b1ea3-2a48-4613-b61a-d1dd1d241bfd
		summarizeBy: none
		sourceColumn: response_id

		annotation SummarizationSetBy = Automatic

	column id
		dataType: int64
		formatString: 0
		lineageTag: a83ca057-1610-4d5b-9939-7244acc5bbeb
		summarizeBy: sum
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column quiz_id
		dataType: int64
		formatString: 0
		lineageTag: bbe14c31-8077-4e90-a905-c43eba73c5fe
		summarizeBy: sum
		sourceColumn: quiz_id

		annotation SummarizationSetBy = Automatic

	column user_id
		dataType: int64
		formatString: 0
		lineageTag: 7502cebc-1add-4b14-958c-82499ab7123a
		summarizeBy: none
		sourceColumn: user_id

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: e47d441a-4484-45f6-bfc5-edbc5a29b1ce
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column orden
		dataType: string
		lineageTag: f03377eb-3c64-426a-8690-b3d8090d7f7b
		summarizeBy: none
		sourceColumn: orden

		annotation SummarizationSetBy = Automatic

	column kpi
		dataType: string
		lineageTag: 70d6162a-14e9-41dd-8fd8-56de1e446dad
		summarizeBy: none
		sourceColumn: kpi

		annotation SummarizationSetBy = Automatic

	column value
		dataType: string
		lineageTag: 3e7705de-8680-4be8-aee1-f23b6100bbf4
		summarizeBy: none
		sourceColumn: value

		annotation SummarizationSetBy = Automatic

	column respuesta
		dataType: string
		lineageTag: ca4b1c78-7d47-43c3-883f-7c5750b3c30f
		summarizeBy: none
		sourceColumn: respuesta

		annotation SummarizationSetBy = Automatic

	column Ciudad
		dataType: string
		lineageTag: f8031f77-86f7-41d7-bb6a-b64a50ded55a
		summarizeBy: none
		sourceColumn: Ciudad

		annotation SummarizationSetBy = Automatic

	column Cadena
		dataType: string
		lineageTag: 4a83aace-ce9e-4bde-93bf-1e23074f895c
		summarizeBy: none
		sourceColumn: Cadena

		annotation SummarizationSetBy = Automatic

	column Subcadena
		dataType: string
		lineageTag: 1151a69e-3243-4673-9131-9433d7f789d7
		summarizeBy: none
		sourceColumn: Subcadena

		annotation SummarizationSetBy = Automatic

	column Sucursal
		dataType: string
		lineageTag: bca2eada-5a80-47a5-9531-01822d9bdd15
		summarizeBy: none
		sourceColumn: Sucursal

		annotation SummarizationSetBy = Automatic

	column 'Foto después' = ""
		lineageTag: 8c6a3124-248e-42e9-8052-3052d6cec2d0
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column quiz_response_id
		dataType: string
		lineageTag: 1cc0d4d7-34b9-4246-9a0d-c2f05054569d
		summarizeBy: none
		sourceColumn: quiz_response_id

		annotation SummarizationSetBy = Automatic

	column keyfoto
		dataType: string
		lineageTag: 31129cbd-9053-43ff-a723-c76aa8433b36
		summarizeBy: none
		sourceColumn: keyfoto

		annotation SummarizationSetBy = Automatic

	column alerta_id
		dataType: string
		lineageTag: bba008f7-4cf0-4c9f-a404-227a435bf903
		summarizeBy: none
		sourceColumn: alerta_id

		annotation SummarizationSetBy = Automatic

	column periodo
		dataType: string
		lineageTag: 3d27ad64-9b4d-436a-84df-e27d8493fb16
		summarizeBy: none
		sourceColumn: periodo

		annotation SummarizationSetBy = Automatic

	partition Mantenimiento = m
		mode: import
		source =
				let
				    Origen = Value.NativeQuery(AmazonRedshift.Database("redshift.infra.tcgscout.com","prod"), "select distinct#(lf)qr.branch_id,#(lf)br.name,#(lf)trunc(CONVERT_TIMEZONE('GMT','GMT+6',qr.started_at)) as fecha,#(lf)qr.branch_id||'|'||trunc(CONVERT_TIMEZONE('GMT','GMT+6',qr.started_at))||'|'||br.id||'|'||qr.user_id  as response_id,#(lf)cast(qr.branch_id||replace(trunc(CONVERT_TIMEZONE('GMT','GMT+6',qr.started_at)),'-','')||qr.user_id as bigint) as id,#(lf)-- CONVERT_TIMEZONE('GMT','GMT+6',qr.started_at) as salida,#(lf)left(CONVERT_TIMEZONE('GMT','GMT+6',qr.started_at),7) as periodo,#(lf)qr.id as quiz_response_id, #(lf)qr.quiz_id,#(lf)qr.user_id,#(lf)q.title,#(lf)q.id as question_id,#(lf)case #(lf)#(tab)when q.id in (298352,298353,298354,298357,298356,298358) then 1#(lf)#(tab)when q.id in (298355,300674,300675,300684,298359,300685) then 2#(lf)#(tab)when q.id in (300676,300677,300678,300687,300686,300688) then 3#(lf)#(tab)when q.id in (300679300680,300681,300690,300689,300691) then 4#(lf)#(tab)when q.id in (300682,300683,300693,300692) then 5#(lf)end as orden,#(lf)case #(lf)#(tab)when q.title ilike '%¿En qué área tienes necesidad de mantenimiento?%' then 'Area'#(lf)#(tab)when q.""type"" = 'photo' then 'Foto'#(lf)#(tab)when q.title ilike '%el detalle%' then 'Comentario'#(lf)#(tab)else qra.value#(lf)end as kpi,#(lf)qra.value,#(lf)case #(lf)#(tab)when q.""type"" = 'choices_single' then qc.title#(lf)#(tab)when q.""type"" = 'photo' then 'https://tcgscout.com/storage/'||qra.value#(lf)#(tab)else qra.value#(lf)end as respuesta,#(lf)q.""type""#(lf)from tcg_scout_v2.quiz_responses qr #(lf)LEFT JOIN tcg_scout_v2.quiz_response_answers qra on qra.quiz_response_id =qr.id #(lf)left join tcg_scout_v2.questions q on q.id = qra.question_id #(lf)left join tcg_scout_v2.question_choices qc on qc.question_id ||qc.value = qra.question_id ||qra.value #(lf)join tcg_scout_v2.branch_quiz bq on bq.id = qr.branch_quiz_id#(lf)join tcg_scout_v2.brands br on br.id = bq.brand_id#(lf)where qr.quiz_id in (6371, 6381)#(lf)and qr.approved is not false#(lf)and qr.deleted_at is null#(lf)and not q.id in (298354,300675,300678,300681,298358,300685,300688,300691,298357,300684,300687,300690,300693,298353,300674,300677,300680,300683)#(lf)and qr.id not in (3465066,3465068,3465069)#(lf)and qr.id NOT IN (4688190, 4866732)", null, [EnableFolding=true]),
				    #"Columnas quitadas" = Table.RemoveColumns(Origen,{"type", "question_id", "title"}),
				    #"Filas filtradas1" = Table.SelectRows(#"Columnas quitadas", each ([kpi] = "Area")),
				    #"Filas filtradas" = Table.SelectRows(#"Filas filtradas1", each [respuesta] <> null),
				    #"Consultas combinadas" = Table.NestedJoin(#"Filas filtradas", {"branch_id"}, Sucursales, {"branch_id"}, "Sucursales", JoinKind.LeftOuter),
				    #"Se expandió Sucursales" = Table.ExpandTableColumn(#"Consultas combinadas", "Sucursales", {"ciudad", "cadena", "subcadena", "sucursal"}, {"Sucursales.ciudad", "Sucursales.cadena", "Sucursales.subcadena", "Sucursales.sucursal"}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Se expandió Sucursales",{{"Sucursales.cadena", "Cadena"}, {"Sucursales.subcadena", "Subcadena"}, {"Sucursales.sucursal", "Sucursal"}, {"Sucursales.ciudad", "Ciudad"}}),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Columnas con nombre cambiado",{{"orden", type text}}),
				    #"Personalizada agregada" = Table.AddColumn(#"Tipo cambiado", "keyfoto", each [response_id]&"|"&[orden]),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Personalizada agregada",{{"quiz_response_id", type text}}),
				    #"Personalizada agregada1" = Table.AddColumn(#"Tipo cambiado1", "Personalizado", each [quiz_response_id]&""&[orden]),
				    #"Columnas con nombre cambiado1" = Table.RenameColumns(#"Personalizada agregada1",{{"Personalizado", "alerta_id"}}),
				    #"Filas filtradas2" = Table.SelectRows(#"Columnas con nombre cambiado1", each [keyfoto] <> null and [keyfoto] <> "")
				in
				    #"Filas filtradas2"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

